project:
  type: website
  output-dir: docs

website:
  title: "P-E Sugier"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: curriculum.qmd
        text: About
      #- href: recherche.qmd
      #  text: Research
      - href: publications.qmd
        text: Publications    
      - href: enseignement.qmd
        text: Teaching

format:
  html:
    theme:
      light: [solar, theme-light2.scss]
      dark: solar #[solar, theme-dark.scss]
      
    css: styles.css
    toc: true
    page-layout: full

editor: visual

